### ISSUE TITLE
Error: While trying to resolve module `http`

### ISSUE THREAD

**Issue by Saurabhreactninja** [bhushankumarl/spreedly-api#3]
While trying to implement spreedly-api in react native.
var spreedly = require('spreedly-api')('environmentKey','accessSecret');
@bhushankumarl can you tell me how i can implement it in react native.
or please share me any demo for react native

![Simulator Screen Shot - iPhone X - 2019-06-04 at 12 56 24](https://user-images.githubusercontent.com/26300876/58859767-373f7e80-86c8-11e9-915a-fb87bf6879be.png)

**Comment by bhushankummar** [comment]
This is working fine in NodeJs 10. Can you please recheck with other examples?

**Comment by devadi1996** [comment]
I am facing the same issue in node version v12.6.0
